### ISSUE TITLE
outreachy.org/eligibility/: Typo

### ISSUE THREAD

**Issue by davidhedlund** [sagesharp/outreachy-django-wagtail#184] opened 2018-03-20 22:45 UTC
In https://www.outreachy.org/eligibility/

"Are you a national or permanent resident of the United States of America? Outreachy is open to some people around the world, and additional grpous of people in the U.S.A."

"grpous" is a typo.

**Comment by sagesharp** [comment] 2018-03-21 13:40
This is a duplicate of #154

**Comment by davidhedlund** [comment] 2018-03-21 13:40
Thank you.

**Closed by sagesharp** 2018-03-21 13:40 UTC
